/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the vanta-auditor-api-sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx auditsList.ts
 */

import { Vanta } from "vanta-auditor-api-sdk";

const vanta = new Vanta({
  bearerAuth: process.env["VANTA_BEARER_AUTH"] ?? "",
});

async function main() {
  const result = await vanta.list({});

  console.log(result);
}

main().catch(console.error);
