workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Conduct an audit:
        inputs:
            - location: api_spec.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/vanta/vanta/conduct-an-audit
targets:
    vanta:
        target: typescript
        source: Conduct an audit
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/vanta/vanta/conduct-an-audit-typescript-code-samples
            blocking: false
