/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { auditorsCreate } from "../../funcs/auditorsCreate.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.AddAuditorInput$inboundSchema,
};

export const tool$auditorsCreate: ToolDefinition<typeof args> = {
  name: "auditors-create",
  description: `Create an auditor

Create an auditor in Vanta.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await auditorsCreate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
