/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { auditsCreateCustomEvidenceRequest } from "../../funcs/auditsCreateCustomEvidenceRequest.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateCustomEvidenceRequestRequest$inboundSchema,
};

export const tool$auditsCreateCustomEvidenceRequest: ToolDefinition<
  typeof args
> = {
  name: "audits-create-custom-evidence-request",
  description: `Create a custom evidence request for an audit

Create a custom evidence request for an audit.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await auditsCreateCustomEvidenceRequest(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
