/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { auditsCreateCommentForEvidence } from "../../funcs/auditsCreateCommentForEvidence.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateCommentForAuditEvidenceRequest$inboundSchema,
};

export const tool$auditsCreateCommentForEvidence: ToolDefinition<typeof args> =
  {
    name: "audits-create-comment-for-evidence",
    description: `Create a comment for audit evidence

Create a comment in Vanta for a piece of evidence.`,
    args,
    tool: async (client, args, ctx) => {
      const [result, apiCall] = await auditsCreateCommentForEvidence(
        client,
        args.request,
        { fetchOptions: { signal: ctx.signal } },
      ).$inspect();

      if (!result.ok) {
        return {
          content: [{ type: "text", text: result.error.message }],
          isError: true,
        };
      }

      const value = result.value;

      return formatResult(value, apiCall);
    },
  };
