/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { auditsListEvidence } from "../../funcs/auditsListEvidence.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListAuditEvidenceRequest$inboundSchema,
};

export const tool$auditsListEvidence: ToolDefinition<typeof args> = {
  name: "audits-list-evidence",
  description: `List audit evidence

Returns a paginated list of evidence for an audit.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await auditsListEvidence(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
