/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { auditsUpdateEvidence } from "../../funcs/auditsUpdateEvidence.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateAuditEvidenceRequest$inboundSchema,
};

export const tool$auditsUpdateEvidence: ToolDefinition<typeof args> = {
  name: "audits-update-evidence",
  description: `Update audit evidence

Update audit evidence.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await auditsUpdateEvidence(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
