/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { auditsList } from "../../funcs/auditsList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListAuditsRequest$inboundSchema,
};

export const tool$auditsList: ToolDefinition<typeof args> = {
  name: "audits-list",
  description: `List audits

Returns a paginated list of audits scoped to the audit firm.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await auditsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
