/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { auditsCreateCustomControl } from "../../funcs/auditsCreateCustomControl.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.CreateCustomControlRequest$inboundSchema,
};

export const tool$auditsCreateCustomControl: ToolDefinition<typeof args> = {
  name: "audits-create-custom-control",
  description: `Create a custom control for an audit

Create a custom control for an audit.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await auditsCreateCustomControl(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
