/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ClosedEnum } from "../../types/enums.js";

export const AuditFocus = {
  External: "EXTERNAL",
  Internal: "INTERNAL",
} as const;
export type AuditFocus = ClosedEnum<typeof AuditFocus>;

/** @internal */
export const AuditFocus$inboundSchema: z.ZodNativeEnum<typeof AuditFocus> = z
  .nativeEnum(AuditFocus);

/** @internal */
export const AuditFocus$outboundSchema: z.ZodNativeEnum<typeof AuditFocus> =
  AuditFocus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AuditFocus$ {
  /** @deprecated use `AuditFocus$inboundSchema` instead. */
  export const inboundSchema = AuditFocus$inboundSchema;
  /** @deprecated use `AuditFocus$outboundSchema` instead. */
  export const outboundSchema = AuditFocus$outboundSchema;
}
